"""Added payment_status field

Revision ID: b5eee00806b4
Revises: 835ffc0758d8
Create Date: 2025-04-29 01:04:17.056411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5eee00806b4'
down_revision = '835ffc0758d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotes')
    op.drop_table('invoices')
    op.drop_table('purchase_orders')
    op.drop_table('bills')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('bill_date', sa.DATE(), nullable=False),
    sa.Column('vendor_name', sa.TEXT(), nullable=False),
    sa.Column('line_items', sa.TEXT(), nullable=False),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('due_date', sa.DATE(), nullable=False),
    sa.Column('payment_status', sa.TEXT(), server_default=sa.text("'Unpaid'"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('po_date', sa.DATE(), nullable=False),
    sa.Column('supplier_name', sa.TEXT(), nullable=False),
    sa.Column('line_items', sa.TEXT(), nullable=False),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('shipping_address', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('invoice_date', sa.DATE(), nullable=False),
    sa.Column('client_name', sa.TEXT(), nullable=False),
    sa.Column('line_items', sa.TEXT(), nullable=False),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('due_date', sa.DATE(), nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'Pending'"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('quote_date', sa.DATE(), nullable=False),
    sa.Column('customer_name', sa.TEXT(), nullable=False),
    sa.Column('line_items', sa.TEXT(), nullable=False),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('validity_period', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
