"""Initial migration

Revision ID: fa6399bec9d7
Revises: 36bde896a66d
Create Date: 2025-05-20 00:58:46.330563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6399bec9d7'
down_revision = '36bde896a66d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('equities')
    op.drop_table('companies')
    op.drop_table('sale')
    op.drop_table('payroll_records')
    op.drop_table('purchase_orders')
    op.drop_table('quotes')
    op.drop_table('invoices')
    op.drop_table('bills')
    op.drop_table('assets_liabilities')
    op.drop_table('financial_records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=False),
    sa.Column('debit', sa.FLOAT(), nullable=True),
    sa.Column('credit', sa.FLOAT(), nullable=True),
    sa.Column('type_of_expense', sa.VARCHAR(length=50), nullable=True),
    sa.Column('type_of_income', sa.VARCHAR(length=50), nullable=True),
    sa.Column('net_expenses', sa.FLOAT(), nullable=True),
    sa.Column('gst_paid', sa.FLOAT(), nullable=True),
    sa.Column('net_income', sa.FLOAT(), nullable=True),
    sa.Column('gst_received', sa.FLOAT(), nullable=True),
    sa.Column('balance', sa.FLOAT(), nullable=True),
    sa.Column('invoice', sa.VARCHAR(length=255), nullable=True),
    sa.Column('company_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets_liabilities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('subcategory', sa.VARCHAR(length=50), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.CheckConstraint("category IN ('Asset', 'Liability')", name='ck_asset_liability_category'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bills',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vendor_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('line_items', sa.TEXT(), nullable=False),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('due_date', sa.DATE(), nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('client_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('line_items', sa.TEXT(), nullable=False),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('due_date', sa.DATE(), nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('line_items', sa.TEXT(), nullable=False),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('validity_period', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('supplier_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('line_items', sa.TEXT(), nullable=False),
    sa.Column('total_amount', sa.FLOAT(), nullable=False),
    sa.Column('shipping_address', sa.TEXT(), nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_records',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('employee_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('gross_wages', sa.FLOAT(), nullable=False),
    sa.Column('payg_withholding', sa.FLOAT(), nullable=True),
    sa.Column('superannuation', sa.FLOAT(), nullable=True),
    sa.Column('deductions', sa.FLOAT(), nullable=True),
    sa.Column('net_pay', sa.FLOAT(), nullable=False),
    sa.Column('company_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('sale_date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('abn_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('tfn_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('contact_person', sa.VARCHAR(length=100), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
